yext/search-ui-react

.github/workflows/coverage.yml
add coveralls github action
J=SLAP-1920
TEST=manual
see that it work with a dummy repo
=> coverage github action

tests/components/LocationBias.test.tsx
Added automated tests for the LocationBias component that address:
1. all elements of the component are rendered properly (displayName, attribution message, "Update your location" button)
2. setUserLocation uses coordinates returned by getUserLocation to set the updated location
3. clicking on "Update your location" properly renders new displayName if it is changed
4. correct attribution messages are rendered
5. absence of displayName correctly renders nothing
J=SLAP-2109
TEST=auto
=> Add testing for LocationBias component

THIRD-PARTY-NOTICES, package-lock.json, package.json, test-site/package-lock.json
Updates answers-headless-react to the newest version which exports SandboxEndpoints
J=SLAP-2106
TEST=manual
console.log SandboxEndpoints in test site
=> update answers-headless-react to version that exports SandboxEndpoints

tests/__fixtures__/data/filtersearch.ts, tests/components/FilterSearch.stories.tsx, tests/components/FilterSearch.test.tsx
This PR adds Jest tests for the FilterSearch component.
J=SLAP-2108
TEST=auto
=> Jest tests for FilterSearch component

tests/components/LocationBias.test.tsx
=> remove console log in test

tests/components/ResultsCount.test.tsx
This PR adds Jest tests for the ResultsCount component.
J=SLAP-2137
TEST=auto
=> Jest tests for ResultsCount component

package-lock.json, package.json
Added BSD-3-Clause to license in package.json and package-lock.json
J=SLAP-2162
TEST=none
=> updated license in package.json

THIRD-PARTY-NOTICES, package-lock.json, package.json, src/components/ApplyFiltersButton.tsx, src/components/Filters/RangeInput.tsx, src/components/Pagination.tsx, src/components/SearchBar.tsx, src/components/VerticalResultsDisplay.tsx, src/utils/filterutils.tsx, tests/__fixtures__/core/AnswersCore.ts, tests/__fixtures__/data/directanswers.ts, tests/__fixtures__/data/filtersearch.ts, tests/__fixtures__/utils/location-operations.ts, tests/components/AppliedFilters.stories.tsx, tests/components/DirectAnswer.test.tsx, tests/components/Dropdown.test.tsx, tests/components/FilterSearch.test.tsx, tests/components/NumericalFacets.stories.tsx, tests/components/StandardFacets.stories.tsx, tests/components/UniversalResults.test.tsx
Addresses styling nits from new rules.
J=SLAP-2135
TEST=none
=> update eslint-config-slapshot to 0.4.0

.github/workflows/run-linting.yml, package.json, src/components/cards/standard/StandardCard.tsx, tests/__fixtures__/core/AnswersCore.ts
TEST=manual
Set ESLint Warnings to Errors and saw the PR check fail. Reverted this change and saw the PR check pass.
=> Add GH Action to run ES Linter on PRs into `main`.

src/components/FilterSearch.tsx
J=SLAP-2181
TEST=manual,auto
Checked that new width on dropdown worked on all screen sizes and that the hovering highlighted the entire width
=> Fixed FilterSearch dropdown width and padding

package.json
This PR adds description and keywords to package.json. The description is copied from README and keywords provided by product.
J=SLAP-2190
TEST=manual
=> add description and keywords to package.json

test-site/src/pages/PeoplePage.tsx, test-site/src/pages/ProductsPage.tsx, test-site/src/pages/UniversalPage.tsx
=> Update test-site to run search on load

src/components/FilterGroup.tsx
Follow-up to (#245) - jest tests didn't catch the bug :(
=> Fixed bug that tried to set a read-only dict

.github/workflows/sync-sites-branch.yml
update github action to sync main to test-site branch
J=SLAP-2290
=> sync main to test-site branch

.github/workflows/coverage.yml
=> test coverage github action on push

docs/search-ui-react.getuserlocation.md, docs/search-ui-react.md, src/utils/location-operations.ts, tests/operations/location-operations.test.tsx
Wrote a few jests to test the call of `getUserLocation` in different cases. Also fixed a small typo in `location-operations` docs.
J=SLAP-2322
TEST=auto
=> Added location-operations jests

THIRD-PARTY-NOTICES, package-lock.json, package.json, src/components/FieldValueDirectAnswer.tsx, test-site/src/App.tsx, tests/hooks/useStateUpdatedOnSearch.test.tsx, tests/scripts/start-storybook.sh, tests/tsconfig.json
use new alpha version for headless-react, update DirectAnswer component due to ts error related to the new HoursDirectAnswer interface
=> Alpha version for QA

THIRD-PARTY-NOTICES, package-lock.json, package.json, test-site/package-lock.json
Update package version to v1.1.0-beta.335.
=> Update version to v1.1.0-beta.335

package-lock.json
Update `decode-uri-component` and `loader-utils` to address Snyk vulnerabilities in older versions of those packages.
J=none
TEST=none
=> Address Snyk vulnerabilities

.github/CODEOWNERS, .gitignore, THIRD-PARTY-NOTICES, package-lock.json, package.json, src/components/SearchBar.tsx, test-site/package-lock.json, test-site/src/config.ts
Bump the version number and search-headless-react version
J=BACK-2237
TEST=manual
Manually used the test site and tested that the cloudRegion and environment properties affected the endpoints used when making requests
=> Version 1.2.0

src/components/SearchBar.tsx
removed logo from search bar and increased height of search field
J=BACK-2305
T=manual
Ran test site locally and also checked with UX team
=> Remove logo searchbar

src/components/SearchBar.tsx, src/components/utils/renderAutocompleteResult.tsx
Before: https://drive.google.com/file/d/1L-D8lFfdWw53uBAQ4pU2fxuvtAlOOahj/view?usp=sharing
After: https://drive.google.com/file/d/15Jd5jZ0yXMoDTWMrOT1VsqspbmV0bePc/view?usp=sharing
J=BACK-2239
TEST=manual
ran on test site and verified with product team
=> truncate search autcomplete results and prevent resizing

test-site/package-lock.json, test-site/package.json, test-site/src/components/HTMLExampleCard.tsx, test-site/src/components/MarkdownExampleCard.tsx, test-site/src/styles/resetStyles.css
Introduce card examples for rendering the new lexical field as html, and the new markdown field. (#385)
=> Card examples for rendering rich text results

THIRD-PARTY-NOTICES, package-lock.json, package.json, test-site/package-lock.json
Bump package.json to v1.4.0 and search-headless-react to v2.4.0.
=> Prepare v1.4.0

package-lock.json, package.json, test-site/package-lock.json
- Add `onDropdownInputChange` optional prop to `FilterSearch` component (#421)
- Support React 18 (#423)
- Resolve vulnerabilities (#422)
=> Bump package version to 1.5.0-beta.426

src/hooks/useSearchWithNearMeHandling.ts
If the autocomplete endpoint is unavailable, we won't configure the endpoint for query/search. This change fixes that, so we will at least set up the endpoint. 
The effect of this is allowing the "no results" message to show up in Storm Test Search when there is a server error (for example).
Tested by running local tests and spinning up test-site
=> Gracefully Degrade initial Autocomplete before query

docs/search-ui-react.generativedirectanswerprops.citationcard.md, docs/search-ui-react.generativedirectanswerprops.citationscontainer.md, docs/search-ui-react.generativedirectanswerprops.md, package-lock.json, package.json, src/components/GenerativeDirectAnswer.tsx
TEST=manual
verified it functions as before on test-site. Verified it no longer cause rendering error in ALPHA
=> Fix hook issues caused by citations rendering

THIRD-PARTY-NOTICES, package-lock.json, package.json, test-site/package-lock.json
Updating the @babel/plugin-transform-runtime import from 7.18.5 to 7.23.2 to resolve a potential vulnerability.
J=VULN-39418, VULN-39419
TEST=manual
Ran `npm run start` in test-site, site functioned as expected.
Saw package versions were updated in package-lock.json.
=> Resolve Vulnerability
