yext/search-ui-react

src/components/Dropdown/DropdownInput.tsx, src/components/SearchBar.tsx
This prop allows users of `DropdownInput` to optionally add an `aria-label`
to the `input` element. This is especially useful when using the Component
with buttons such as the clear button or the `DropdownSubmitButton`.
J=SLAP-2058
TEST=auto
Verified that Storybook no longer reported WCAG violations for the `SearchBar`.
=> Add optional `aria-label` prop to `DropdownInput`.

src/components/Dropdown/DropdownInput.tsx
This prevents default browser autocomplete, which generally
corresponds to recently searched items.
J=SLAP-2050
TEST=manual
added name="name" to the DropdownInput's input, since my browser has
autocomplete values saved for that input name. Saw the default browser
autocomplete show up. Added autocomplete="off", saw it disappear.
=> add autocomplete="off" to DropdownInput

package.json, tailwind.config.js, test-site/package-lock.json
Distribute a Tailwind CSS bundle so that a Tailwind build chain isn't required in order to get the component styling
J=SLAP-2051
TEST=manual
In the test-site, delete the tailwind.config.js file and import `@yext/answers-react-components/bundle.css` and see the built-in component styling working correctly on the page.
=> Distribute Tailwind CSS Bundle

THIRD-PARTY-NOTICES, package-lock.json, package.json, src/components/Dropdown/Dropdown.tsx, src/hooks/useRecentSearches.ts
Adds defaulting for `<pkg>.default` imports, since `<pkg>.default` does not exist in deno or on the browser, but is still necessary for node
=> add defaulting for deno

package.json
Tailwind does not automatically pick up on tailwind.config.cjs as a config file,
unlike tailwind.config.js .
In the future we probably want some automated way to test this.
J=NONE
TEST=manual
in the test-site, remove the tailwind config and comment out index.css contents
using the bundle.css shows correct styling
before the change, would not have correct styling
(for testing purposes, turned off type: module for both the component lib and answers-headless-react
due to type: module not working with create-react-app)
unminified, after running a css formatter, bundle.css was a little under 300 lines long
now, unminified, bundle.css is 1300 lines long
=> specify cjs tailwind config in css build

.storybook/preview.js
Product confirmed only wcag standards up to level AA is required. Remove wcag2aaa check for storybook.
J=SLAP-2056 & SLAP-2059
TEST=manual
see the color contrast violation from level AAA no longer appear in storybook's Spellcheck and AppliedFilters stories.
=> remove wcag2aaa in storybook test

src/components/ThumbsFeedback.tsx, src/components/cards/standard/StandardCardDisplay.tsx
This PR fixes the WCAG issues from displaying thumbs feedback in `DirectAnswer` and `StandardCard` components.
The only remaining WCAG issues in Storybook are those from when a component is loading and at half opacity. Because components in this state are inactive, WCAG color contrast requirements don't apply (see Guideline 1.4.3 in [WCAG 2.0](https://www.w3.org/TR/2008/REC-WCAG20-20081211/)).
J=SLAP-2057
TEST=manual
Check that the WCAG issues for insufficient color contrast and missing button labels no longer appear in Storybook for the Field Value and Featured Snippet stories for `DirectAnswer`. See that now only Loading stories have WCAG issues and only for insufficient color contrast.
=> Fix DirectAnswer WCAG issues

tests/components/ResultsCount.stories.tsx
Add 2 stories for ResultsCount component:
- Primary - results count display for vertical page
- Loading - result is in loading state
J=SLAP-2093
TEST=manual
=> Add stories for ResultsCount component

tests/__fixtures__/data/verticalnoresults.ts, tests/components/AlternativeVerticals.stories.tsx
Add storybook stories for AlternativeVerticals component:
- Primary: standard configuration for AlternativeVerticals, with displayAllOnNoResults as false
- DisplayAllOnNoResults: standard configuration for AlternativeVerticals, with displayAllOnNoResults as true
- Loading: search is in loading state
J=SLAP-2090
TEST=manual
=> add stories for AlternativeVerticals

tests/components/Pagination.stories.tsx
Add 6 stories for Pagination component:
- Primary: pagination UI for a results count of a search
- PaginateAllOnNoResults: pagination UI using total results count of a vertical when there's no results from a search
- OnMidPageWithEllipses:  UI when user is on the middle page number of the result set, with many more pages on each side of it which would collapse into ellipses.
- OnMidPage:  UI when user is on the middle page number of the result set, no ellipses.
- OnLastPage: UI when user is on the last page number of the result set
- Loading: when a search is in loading state
J=SLAP
TEST=auto
see that percy build captured all the new snapshots
=> Add stories for Pagination component

tests/__fixtures__/data/filtersearch.ts, tests/components/FilterSearch.stories.tsx
This PR adds 3 stories for the `FilterSearch` component.
- Primary: text input with dropdown closed
- DropdownUnsectioned: dropdown expanded with default, unsectioned results
- DropdownSectioned: dropdown expanded with sectioned results
J=SLAP-2091
TEST=auto
=> Add stories for FilterSearch

tests/components/AlternativeVerticals.test.tsx
Added jest tests for AlternativeVerticals component that checks if the href and label of the vertical and universal links are as expected, using the default and custom `getSuggestionUrl` function. Also, a jest test for when there's no vertical suggestions from the response.
Since there's already UI check for `verticalConfigMap` and `displayAllOnNoResults` config option from storybook for AlternativeVerticals, there's no jest tests added for it.
J=SLAP-2107
TEST=auto
see that jest tests passed
=> Add jest tests for AlternativeVerticals component

.storybook/preview.js, src/components/UniversalResults.tsx, tests/__compound-components__/Filters/Facets.tsx, tests/__compound-components__/Filters/HierarchicalFacet.tsx, tests/components/AlternativeVerticals.stories.tsx, tests/components/AppliedFilters.stories.tsx, tests/components/DirectAnswer.stories.tsx, tests/components/FilterSearch.stories.tsx, tests/components/Filters/Facets.stories.tsx, tests/components/Filters/HierarchicalFacet.stories.tsx, tests/components/LocationBias.stories.tsx, tests/components/Pagination.stories.tsx, tests/components/ResultsCount.stories.tsx, tests/components/SearchBar.stories.tsx, tests/components/SpellCheck.stories.tsx, tests/components/UniversalResults.stories.tsx, tests/components/VerticalResults.stories.tsx
This PR adds Storybook controls for each component's stories. This allows almost all component props to be configured from the Storybook UI. Props that are functions or objects containing functions (e.g. `onSearch`, `onClick`, `renderEntityPreviews`, etc.) cannot be directly configured via the controls (see https://storybook.js.org/docs/react/essentials/controls#dealing-with-complex-values).
Additionally, there are a few props that can be set, but their values don't affect the components because we are hardcoding the returned response results. I disabled the controls for these, but if we want to update the response based on those props in the future, they can easily be added back:
- `hierarchicalFacetsDelimiter` in `AppliedFiltersDisplay`
- `sectioned` and `searchFields` in `FilterSearch` …
=> Add Storybook controls

src/components/Filters/CheckboxOption.tsx, test-site/src/pages/PeoplePage.tsx, tests/__fixtures__/data/filters.ts, tests/components/StaticFilters.test.tsx
This PR adds Jest tests for the higher-level `StaticFilters` component.
J=SLAP-2111
TEST=auto
Check that the added Jest tests pass.
=> Add Jest tests for StaticFilters

package-lock.json, package.json, tests/__setup__/resolver.ts
This PR upgrades Jest from v27 to v28. Most of the breaking changes don't affect us, except for two:
- To use the JSDOM test environment, `jest-environment-jsdom` now has to be installed separately
- Jest now has full support for package exports, which can cause problems where file imports are not resolved correctly. Specifically, this is a problem for `uuid`. There is a discussion and proposed solution in this [GitHub issue](https://github.com/microsoft/accessibility-insights-web/pull/5421#issuecomment-1109168149), which I used in this PR. To summarize, the fix is to add a custom resolver that forces Jest to use the CommonJS+node version of `uuid`, but leaves all other resolutions the same
J=SLAP-2123
TEST=auto
See that Jest tests pass.
=> Upgrade Jest to v28

docs/answers-react-components.usecomposedcssclasses.md, etc/answers-react-components.api.md, src/components/AlternativeVerticals.tsx, src/components/AppliedFilters.tsx, src/components/ApplyFiltersButton.tsx, src/components/DirectAnswer.tsx, src/components/FilterSearch.tsx, src/components/Filters/CheckboxOption.tsx, src/components/Filters/HierarchicalFacetDisplay.tsx, src/components/Filters/RangeInput.tsx, src/components/LocationBias.tsx, src/components/Pagination.tsx, src/components/ResultsCount.tsx, src/components/SearchBar.tsx, src/components/SpellCheck.tsx, src/components/ThumbsFeedback.tsx, src/components/UniversalResults.tsx, src/components/VerticalResultsDisplay.tsx, src/components/cards/standard/StandardCardDisplay.tsx, src/components/sections/SectionHeader.tsx, src/components/sections/StandardSection.tsx, src/components/utils/renderAutocompleteResult.tsx, src/hooks/useComposedCssClasses.tsx, test-site/package-lock.json
This PR makes each component's `builtInCssClasses` readonly.
I opted to use the Typescript `Readonly` utility type which adds `readonly` to each of the properties of an object. Although, this is a shallow operation, in the case of the `builtInCssClasses`, this is sufficient because the object will only contain properties with string values. I initially tried using const assertions, but because we define the type for the classes, such as `const builtInCssClasses: SearchBarCssClasses = { ... }`, it seems to override the const assertion and allows the properties to be modified.
J=SLAP-2136
TEST=manual
Tried modifying the classes in `builtInCssClasses` and saw it gives an error about not being able to assign to read-only properties.
=> Make `builtInCssClasses` readonly

tests/components/AlternativeVerticals.stories.tsx, tests/components/RangeInput.stories.tsx
This PR adds storybook stories for RangeInput, testing:
- basic range input
- disabled input
- valid range
- invalid range
J=SLAP-2146
TEST=manual
=> add stories for RangeInput

src/components/FilterSearch.tsx, tests/__fixtures__/data/filtersearch.ts, tests/components/FilterSearch.test.tsx
This PR changes FIlterSearch such that you can only have one filter at a time.  When you add the first filter, it is set as a filter option for the next search.  Upon further addition of searched filters, the old ones will be replaced by the newly searched ones.  Note that backspacing from the filter box does not remove the filter (just as ZocDoc does for its doctor filter).
J=SLAP-2142
TEST=auto
One jest test was added to test the added functionality.
=> Remove old filter values

src/components/Filters/RangeInput.tsx, tests/components/RangeInput.test.tsx, tests/components/SpellCheck.test.tsx
This PR adds Jest tests for RangeInput component. Tests were not passing in the first commit because of an error in useEffect function of RangeInput - instead of returning nothing, it returned a non-function.
J=SLAP-2145
TEST=auto
=> Jest tests for RangeInput component

src/hooks/useSearchWithNearMeHandling.ts, src/utils/filterutils.tsx
Consolidate the import statements from Headless-React since there were multiple in `useSearchWithNearMeHandling` and `filterutils.ts`. Change the `clearStaticRangeFilters` function's `answersActions` param type from `AnswersHeadless` to `AnswersActions` in`filterutils.ts`.
J=SLAP-2189
TEST=auto
Check that tests still pass and that calls to `clearStaticRangeFilters` are unchanged.
=> Update a few import statements and types

src/components/FilterSearch.tsx
This PR makes hovering over filter search autocomplete suggestions trigger a highlight on the selected option.  The JIRA item requested that the `focusedOption` CSS should be applied to options that are hovered over.  However, adding a `hover` style to `option` more closely replicates what is done in `SearchBar` and seems to be a more straightforward approach.
(Unfortunately screenshots do not show cursors.  Cursor is over 'first name 1', not selected with arrow keys.)
J=SLAP-2179
TEST=manual
Attempted to add hovering test to storybook, but ran into issues with simulating hover.
=> added hover styling to "option"

.github/workflows/run-linting.yml
This PR replaces actions in the linter workflow with reusable linting workflow in slapshot-reusable-workflows.
J=SLAP-2180
TEST=auto
=> Use linting workflow from reusable workflow

README.md
This PR adds documentation to readme for /bundle.css. 
J=SLAP-2197
TEST=manual
Tested on test-site, the styling works after removing tailwind config and importing /bundle.css.
=> add documentation for /bundle.css to README

src/components/ApplyFiltersButton.tsx, src/components/SearchBar.tsx
This PR fixes a bug where clicking the `ApplyFiltersButton` did not reset the pagination offset. Also, it includes a fix that I made in the `react-16.8` branch to only include recent searches screenreader counts when on a universal page.
J=SLAP-2202
TEST=manual
Checked that previously, navigating to the second page on the `people` vertical and selecting a filter with the apply filters button would not reset the offset, but after the fix, it resets to the first page.
=> Fix `ApplyFiltersButton` offset

tests/components/SearchBar.stories.tsx
This PR fixes the `SearchBar` stories so they display recent searches as expected. Adding recent searches manually to the browser's local storage was causing problems. This is likely because of the hard-coded timestamp, which may cause the data to be removed from storage if it is too far in the past. I changed the recent searches back to being added using `userEvent`s.
J=none
TEST=auto
See that Percy snapshots include the recent searches for `SearchBar` stories that have the dropdown expanded.
=> Fix SearchBar stories

src/components/Filters/StaticFiltersProvider.tsx
update className's default styling from `md-56` to `md:w-56`
J=SLAP-2207
TEST=manual
include only StaticFilters on the left hand side of people page. With `md:w-56`, see that the width of it now changes when the page size changes from >768px to <768px
=> fix StaticFiltersProvider styling

src/components/ResultsCount.tsx
This PR fixes the line break problem in resultsCount when the window is small and would not fit the resultsCount text and the applied filters in one line. Instead of splitting the resultCount into two lines when the window is too small, it now keeps resultsCount in one line and puts some of applied filter onto the second line.
J=SLAP-2206
TEST=manual
=> fixed line break bug in resultsCount

src/components/ApplyFiltersButton.tsx, src/components/Filters/FacetsProvider.tsx, src/components/Filters/RangeInput.tsx, src/components/NumericalFacets.tsx, src/utils/filterutils.tsx, test-site/src/pages/PeoplePage.tsx, test-site/src/pages/ProductsPage.tsx
This PR fixes a bug where range input static filters were removed when selecting/de-selecting facet options with different `fieldId`s. The expected behavior is that these static range filters are removed when conducting a new search (existing behavior), or only when a numerical facet option with the same `fieldId` is applied (fixed behavior).
J=SLAP-2213
TEST=manual
In the test-site, see that
- applying a static range filter, clearing the input, and then applying a numerical facet option for the same filter group removes the static range filter (existing behavior)
- applying a static range filter and then selecting or de-selecting a facet option from a different filter group leaves the static range filter as is (new behavior)
- conducting a new search removes facet options and static …
=> Fix static range filter bug

src/components/Filters/RangeInput.tsx, tests/components/RangeInput.test.tsx
This PR adds a 'clear filter' feature for 'clear min and max' button in RangeInput as suggested by product, so that the button does not only clear the input itself but also the range filter that is applied. The test file has also been changed so that it will check whether the range filter is cleared in state when using the clear button.
J=SLAP-2212
TEST=manual
Test: applied range input filter and clicked the clear button, it removes the applied range filter. Also tested with other applied filters, clicking on clear button for range input filter does not clear other filters as expected.
=> add clear filter feature for 'clear min and max' button in RangeInput

src/components/Filters/FacetsProvider.tsx, src/components/Filters/RangeInput.tsx, src/components/Filters/StaticFiltersProvider.tsx, test-site/src/pages/PeoplePage.tsx, test-site/src/pages/ProductsPage.tsx
Per product's feedback, update default width styling to be `w-full` and have user use a container element to control sizing instead. Update pages in test-site to have the div container of the filters/facets specify a fixed width.
J=SLAP-2214
TEST=manual
spin up test-site, toggle collapse/expand button on employee department facet on different screen size and see that layout remain fixed (not shifting when toggle).
=> fix layout shift issue with filter/facet components

src/components/Filters/RangeInput.tsx
This PR fixes inputPrefix collision issue in RangeInput. The padding with inputPrefix is increased to avoid potential collision of max(min) input with the inputPrefix for up to three characters. The max/min input is also aligned to the right as approved by product.
J=SLAP-2212
TEST=manual
Tested the change by adding an inputPrefix of three characters (USD) to NumericalFacets. With padding increased, the max/min input no longer collides with inputPrefix. The min/max input was aligned to the right because of aesthetic reason approved by product - so without any input, the min/max placeholder and inputPrefix would not appear cramped together - input numbers appeared as expected with the right alignment.
=> fix inputPrefix collision issue 

src/components/FilterSearch.tsx, test-site/src/pages/PeoplePage.tsx, tests/components/FilterSearch.test.tsx
This PR fixes a bug where facets were not being reset when applying a filter from `FilterSearch` with `searchOnSelect=true`. Product wants the behavior to be like conducting a search from the search bar, where facets are cleared. I also moved the `setOffset` call so it is only made when a search is executed, not whenever a filter is selected (e.g. when `searchOnSelect=false`).
J=SLAP-2240
TEST=auto, manual
Check that the updated Jest tests pass. In the test-site, see that before the changes, facets remained when selecting a filter, even if that sometimes led to no results being shown. After the changes, see that facets are removed when selecting a filter from `FilterSearch`.
=> Reset facets on searches from FilterSearch

src/components/SearchBar.tsx, src/hooks/useRecentSearches.ts, tests/hooks/useRecentSearches.test.tsx
This PR allows recent searches to show in verticals and keeps their recent search histories separate.
J=SLAP-2241
TEST=manual, auto
The test site was used to check that recent search histories in different verticals (and in universal) were all kept separate. Jest tests were written for the `useRecentSearches` hook, testing that recent searches appear, that they stay on their own verticals, and that they can be cleared using the returned `clearRecentSearches` function.
=> Separate recent searches in verticals

package-lock.json
Multiple transitive dependencies of Storybook were flagged as Snyk vulnerabilities: unset-value, glob-parent, and file-system-cache. I manually edited the package-lock.json to bump the versions of these dependencies. The new versions do not have the Snyk flagged vulnerabilities. In both cases, I had to bump the version to a new major. I read through the release notes for both transitive dependencies and the breaking changes should not impact us. 
TEST=manual
Built and served the Storybook site. Everything worked as expected.
=> Update Snyk transitive dependencies.

src/components/Dropdown/Dropdown.tsx, tests/hooks/useRecentSearches.test.tsx
InitialValue is not use by FilterSearch or SearchBar. In the case of user want to set an initial value for the search bar, they would set it through answersActions.setQuery() function, which updates on second render, whereas initialValue is set in useState call in useInputContextInstance on first render. This behavior is taken care of by `parentQuery` field already.
J=SLAP-2249
=> remove initialValue in Dropdown

src/components/FilterSearch.tsx
regression from switching from absolute to relative in [previous pr](https://github.com/yext/search-ui-react/pull/205) when changing filter search styling so the width of the dropdown menu match the width of the input box. However this cause the filter dropdown menu to push the content down when it's active. Setting z-index with relative on an element inside that block will only alter its layer with respect to other elements inside the same block.
This pr update the styling back to using absolute but set the dropdown menu to be relative to the filter search container and use `w-full` to span its width such that it match the width of the input box.
J=SLAP-2282
TEST=manual
Before and after:
=> fix styling issue: filterSearch dropdown pushing content down

src/components/ApplyFiltersButton.tsx
Previously, custom styling would replace default styling. use `useComposedCssClasses` to properly merge default tailwind styling with user custom styling.
J=SLAP-2284
TEST=manual
update ApplyFiltersButton in PeoplePage to include `customCssClasses={{ button: "mt-2 text-red-600" }}` and see that the the custom styling is merged with the default instead of replacing it.
=> use useComposedCssClasses in ApplyFiltersButton

tests/components/StaticFilters.stories.tsx, tests/components/UniversalResults.stories.tsx, tests/components/VerticalResults.stories.tsx
Add 2 stories for `StaticFilters`: one with the default props with an option selected and one with `searchable = true`. Also, fix errors in `UniversalResults` and `VerticalResults` stories now that the props require a type param.
J=SLAP-2286
TEST=manual
Check that the new Percy snapshots look as expected.
=> Add StaticFilters stories

src/components/SearchBar.tsx, test-site/package-lock.json
This PR fixes the bug from [this Slack thread](https://yext.slack.com/archives/C032CKFARGS/p1658949929942189)  where query filters were not being applied except when hot-reloading the page. Applied query filters are not returned in the response if an empty array of facet options is sent in the request. Because facets were de-selected rather than cleared out completely when executing a new search from the search bar, no query filters were applied.
J=none
TEST=manual
Check that the correct filters are applied automatically when searching "Marty", "Bleecker", and "Marty frodo". If they correspond to a facet, then the applied filters are removable and don't get "stuck" as applied. Query filters are only applied again after a new search is run from the search bar.
=> Fix bug with applying query filters

src/components/AppliedFiltersDisplay.tsx
I assumed that displayNames would be unique for NLP filters coming from
the API. This is not necessarily the case, and results in duplicate keys
which can result in UI bugs.
Including an underscore and index at the end makes the keys effectively unique barring
very weird edge cases.
J=none
TEST=manual
searching for Richmond on a locations page (does not exist yet, will be introduced in Alex's maps pr)
then searching for texas, does not result in an incorrect UI state
=> unique keys for applied filters

src/components/FilterSearch.tsx, tests/components/FilterSearch.test.tsx
fixed two edge cases that Juliann pointed out
- https://github.com/yext/search-ui-react/pull/256#issuecomment-1205532847
- https://github.com/yext/search-ui-react/pull/256#issuecomment-1205658494
deselecting the filter `onToggle` messed up these two behaviors because it didn't recognize the input in the search filter as a selected filter, and decided not to clear it / keep the filter on the page. 
TEST=auto
=> fix edge cases from filtersearch-option pr

.github/workflows/coverage.yml
Add/update comment for code coverage percentages on pull_request event only.
TEST=manual
made a non dev/ test branch and push the same changes to it. see that the ` individual_coverage_percentages` job was cancelled.
https://github.com/yext/search-ui-react/runs/7694568793?check_suite_focus=true
https://github.com/yext/search-ui-react/tree/test-coverage-githubaction
=> code coverage percentages job on pull_request event

package.json
This directory contains types and interfaces outlining data models.
There are no function or anything of the like to unit test.
TEST=auto
Re-ran the `test` command and saw this directory excluded from the
coverage collection.
=> Exclude `src/models` from Jest Coverage Collection.

tests/operations/search-operations.test.ts
No test was written for `getSearchIntents` as that's essentially a pass through to `executeAutocomplete`.
J=SLAP-2321
TEST=auto
Ensured all unit tests passed.
=> Add Jest Tests for the Search Operations utilities.

.storybook/preview.js, src/components/Dropdown/DropdownInput.tsx, tests/components/Dropdown.stories.tsx, tests/components/SearchBar.stories.tsx
Added stories for `Dropdown` component. Though it is used in `FilterSearch` and `SearchBar`, we figured it'd be good to have separate stories because users should be able to use `Dropdown` for their own components. `Dropdown` doesn't have any built-in css, so I used the `FilterSearch` css as a reference for styling.
On writing the tests, I found a wcag bug with `DropdownInput` that wasn't setting the `aria-activedescendant` correctly on select. I had to set `focusedIndex` back to `-1` after performing actions related to pressing 'enter'. 
J=SLAP-2320
TEST=auto
=> Added Dropdown Stories

THIRD-PARTY-NOTICES, package-lock.json, package.json, src/components/DirectAnswer.tsx, src/components/FieldValueDirectAnswer.tsx, test-site/package-lock.json, tests/__fixtures__/data/directanswers.ts, tests/components/DirectAnswer.stories.tsx, tests/components/DirectAnswer.test.tsx, tests/components/FieldValueDirectAnswer.test.tsx
Added FieldValueDirectAnswer to handle all the built in field types for field value direct answer. Note, we currently do not support internationalization so addresses will be written as if they are US addresses.
in nidhi's PR for featured snippet direct answer, she will implement the logic to handle rich text field type using react-markdown library. So, the switch case for rich_text in FieldValueDirectAnswer will be updated once that is done. Along with the tests for rich_text.
J=SLAP-2332
TEST=auto
added storybook and jest tests for the different field types in field value direct answer
=> FieldValueDirectAnswer component

README.md, test-site/package-lock.json, test-site/package.json, test-site/src/App.tsx, test-site/src/utils/acquireSessionId.ts
The README was updated to reflect the fact that `SearchHeadlessProvider` now takes in a Headless instance. The README also shows someone how to handle acquisition of a session tracking ID. I added session tracking logic to the test-site as well as a further reference.
TEST=auto
Ensured that all unit and WCAG tests passed locally.
=> Further updates to account for changes in `SearchHeadlessProvider`.

README.md
update readme wording now that `SearchHeadlessProvider` requires a `SearchHeadless` instance instead of directly passing in the credentials. Also include small changes such that the code sample works out of the box.
TEST=manual
copy and pasted the code sample to test-site App.tsx using the actual credentials, See that it works as expected.
=> update readme "Getting Started" section

src/components/FeaturedSnippetDirectAnswer.tsx, src/components/FieldValueDirectAnswer.tsx
Per product's request: "good with displaying rich text direct answer as unrendered markdown for now, with the accompanying console warning." This pr added console warn in field value and featured snippet direct answer dealing with rich text field type. Also use JSON.stringify() on result of rich text and hours to avoid potential React errors such as `Objects are not valid as a React child`
=> console warn for no render markdown support

test-site/package-lock.json
Upgrade `ejs`, `async`, and `terser` in the test-site to address vulnerabilities in older versions of those packages.
J=none
TEST=none
=> Address test-site dependency vulnerabilities

docs/search-ui-react.mapboxmap.md, src/components/MapboxMap.tsx, tests/components/MapboxMap.test.tsx
added jest tests for Mapbox component, specifically for the two prop fields: `getCoordinate` and `onDrag`. The remaining props are best tested through storybook.
note that `mapbox-gl` is mocked as it seems to use some web browser functionality on initialization that is not supported in jest test environment (jsdom). Without mocking, jest would present an error `Error: Failed to initialize WebGL.`.
- tried third party libraries `jest-webgl-canvas-mock` and `jest-canvas-mock` still result in more window properties access related errors (`[TypeError: e.window.Worker is not a constructor]`, which could be resolve by [manually mocking Worker](https://github.com/facebook/jest/issues/3449), `[TypeError: this.target.addEventListener is not a function]`...).
- Looked into how pageJS test mapbox …
=> mapbox component jest tests

package-lock.json, package.json, test-site/package-lock.json
Add react-dom as a peer dependency as it's now use in Mapbox component.
Note that, ReactDOM.render is deprecated in React 18, which now have a new client render function `createRoot`. For now, a warning will display in console informing user that the app will behave as if it’s running React 17 until the code switch to the new API. A new item will be created to address this issue.
TEST=manual
`npm pack` the component lib. Created a new React app using react 17/18, see that react-dom is installed as peer dep (automatically install with npm >=7) and mapbox component is display as expected (there's a warning in React 18).
=> Add react-dom as a peer dependency

.storybook/main.js, THIRD-PARTY-NOTICES, package-lock.json, package.json, src/components/Dropdown/Dropdown.tsx, src/components/Filters/CheckboxOption.tsx, src/components/ScreenReader.tsx, test-site/package-lock.json, test-site/package.json, tests/__setup__/responses/universal-query.tsx, tests/__setup__/responses/vertical-query.ts, tests/components/Dropdown.test.tsx, tests/components/StaticFilters.test.tsx, tests/ssr/utils.tsx, tests/tsconfig.json
This PR is to fix the errors `Warning: Prop "id" did not match. Server: "some-id". Client: "another-id"`, reported in https://yext.slack.com/archives/C032CKFARGS/p1664916209295449
React expects that the **rendered content is identical between the server and the client**. However, our usage of `uuid` means different id is generated from the HTML content generated through SSR vs the first render in client side during hydration process. This is a known issues in React SSR (issues in react repo[[1](https://github.com/facebook/react/issues/4000)][[2](https://github.com/facebook/react/issues/5867)][[3](https://github.com/facebook/react/issues/1137)]) and React released a new hook `useId` in React 18 to address it.
I found three potential solutions for React <18 to **generate unique but …
=> Fix React SSR hydration ID mismatch error

package-lock.json, package.json, src/utils/filterutils.tsx
This hot-fix resolves #294. We had `lodash` as a devDependency, even though it's used in `src`. I also updated the import of `isEqual` in `filterutils.tsx` to follow best practices.
J=SLAP-2404
TEST=none
=> Create hot-fix v1.0.1.

src/components/MapboxMap.tsx, src/components/utils/renderToContainer.tsx, tests/components/utils/renderToContainer.test.tsx, tests/tsconfig.json, tsconfig.json
This PR uses a dynamic imports with a .catch fallback for when react-dom/client does not exist.
MapboxMap code had to be tweaked due to differences between ReactDOM.render and ReactDOM.createRoot().render(). Namely, createRoot() does not modify the container element unless it already exists on the physical page. This means that we can't call document.creatElement('div'), use createRoot, and THEN attach it to the mapbox map. Instead, we have to attach the div to the map first.
This also seems it make it more difficult to unit test, my guess would be because createRoot does not do anything on the server. For now I use some jest.mocks to ensure the right methods are being called in the right environments.
TEST=manual,auto
storybook can start up (react 17)
test site can display custom pin in …
=> use createRoot when possible for rendering pin components

THIRD-PARTY-NOTICES, package-lock.json, package.json, test-site/package-lock.json
Bump the package version to v1.0.2 and update the `search-headless-react` version to v2.0.1 to include the latest patch.
=> Bump to v1.0.2 and update `search-headless-react` version

src/components/FilterSearch.tsx, tests/components/FilterSearch.test.tsx
Update the default behavior of `FilterSearch`:
- On select, clobber other static filters in State that have a `fieldId` that matches with one of the search fields for `FilterSearch`. If there are multiple filters that were clobbered, log a console warning.
- If the static filters state is updated from outside of the component, log a console warning if there are multiple "matching" filters in State and there is no custom `onSelect` prop passed in.
- And if there is no filter currently associated with the component, update the input text to the display name of the first "matching" filter that is selected in State.
- If there are no matching filters in State, clear out the input and filter search response.
Note: We only look for field value filters in State for the "matching" filters. We …
=> Update default FilterSearch behavior

.github/workflows/wcag_test.yml, .storybook/test-runner.ts, tests/components/MapboxMap.stories.tsx
paired with the changes in this [PR](https://github.com/yext/slapshot-reusable-workflows/pull/22) in WCAG workflow, this PR updates the WCAG github action in the repo to pass in the mapbox key. Also updated the wcag test to exclude checking elements coming from mapbox canvas container as any potential violations coming from there is outside of our repo's control.
WCAG github action also run on pull request to feature branch now.
J=SLAP-2458
TEST=auto
see that WCAG github action now passes
=> Fix wcag github action mapbox issues

src/components/FilterSearch.tsx, tests/components/FilterSearch.test.tsx
Update `FilterSearch` to account for special backend logic when searching on the `builtin.location` field. In this case, the backend can return filters on `builtin.region` or `address.countryCode` as well, so these `fieldId`s are also considered "matching" for the component. Filters on these fields can be used to populate the input and should be unselected when a new filter is selected from `FilterSearch`.
J=SLAP-2495
TEST=auto, manual
See that the added Jest tests pass. Spin up the test-site and add static filters on `builtin.region`. See that they are used to populate the `FilterSearch` input, warnings are logged, and the filters are unselected by `FilterSearch` as expected.
=> FilterSearch updates for `builtin.location`

src/hooks/useGeolocationHandler.ts, tests/components/Geolocation.test.tsx
Update `useGeolocationHandler` so that it replaces all location filters with the new filter. In other words, filters on the `builtin.location`, `builtin.region`, and `address.countryCode` fields are all removed when a new filter is selected via the `Geolocation` component. This matches the behavior of `FilterSearch` and ensures the `State` doesn't end up with multiple location filters applied at the same time, which can have unpredictable results from the backend.
J=SLAP-2495
TEST=auto
See that the Jest tests still pass even when the mocked state includes other kinds of location filters besides those on `builtin.location`.
=> Update Geolocation to remove all location fields

.github/workflows/sync-sites-branch.yml
Update the `sync-sites-branch` GH workflow to remove Node 12 deprecation [warnings](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) caused by `mtanzi/action-automerge` and an older version of `actions/checkout`. Since `mtanzi/action-automerge` has not been updated in a couple years, I replaced it with `devmasx/merge-branch`, which seems to be more actively maintained, is more widely used in the [GH Marketplace](https://github.com/marketplace/actions/merge-branch), and doesn't produce warnings.
J=SLAP-2468
TEST=manual
Test on a forked repo and see that the workflow doesn't have any warnings. The default branch of the repo is successfully synced with a test branch with a merge commit titled `Merge <default-branch> into …
=> Remove Node 12 deprecation warnings

.github/workflows/sync-sites-branch.yml
Update the `sync_sites_branch` workflow to use the new reusable workflow.
J=SLAP-2507
TEST=manual
Test on a forked repo and see that a commit to `main` triggers a merge commit to the `storybook-site` and `test-site` branches.
=> Use reusable workflow in sync_sites_branch

THIRD-PARTY-NOTICES, package-lock.json, package.json, test-site/package-lock.json
This PR pins `react-collapsed` to the latest minor version (v3.6.0) that supports React 17. In v3.7.0 and v3.8.0, `react-collapsed` fixed a bug ([Slack thread](https://yext.slack.com/archives/C032CKFARGS/p1671130163844249), [GH issue](https://github.com/roginfarrer/react-collapsed/issues/103)) that occurs when using it with React 18 by introducing a breaking change where they dropped compatibility with React 16 and 17. v3.7.0+ would break a search experience using collapsible facets with React <18. Since they are not able to support both React 17 and 18 together, it seems preferable to pin to a version that can be used with both, but is a little buggy with React 18, rather than fully functional with React 18, but breaks other React experiences.
J=SLAP-2521
TEST=manual
See that collapsible …
=> Pin react-collapsed to minor version

README.md
Update the README to add notes about compatibility with Webpack in response to [this](https://github.com/yext/search-ui-react/issues/357) issue.
=> Add compatibility notes to README

.gitignore, THIRD-PARTY-NOTICES, package-lock.json, package.json, src/components/SearchBar.tsx
This change updates @yext/search-headless-react to version 2.2.0-beta.0 which contains the EU endpoints change. It also bumps @yext/search-ui-react to version 1.2.0-beta.0.
J=BACK-2270
TEST=auto,manual
Ran `npm run test`.
Ran `npx serve .` under test-site/.
=> Update @yext/search-headless-react Version

.github/workflows/run-tests.yml, THIRD-PARTY-NOTICES, package-lock.json, package.json
Pin react-collapsed to v3.6 which only supports React 16 and 17 and drop our official React 18 support.
J=TECHOPS-8972
TEST=manual
Created a pages test site following the Hitchhiker module and successfully added
StandardFacets and NumericalFacets to the page. Confirmed react-collapsed v3.6 was
installed.
=> Version 1.2.1

docs/search-ui-react.facetscssclasses.md, docs/search-ui-react.hierarchicalfacets.md, docs/search-ui-react.hierarchicalfacetsprops.md, docs/search-ui-react.md, docs/search-ui-react.numericalfacets.md, docs/search-ui-react.numericalfacetsprops.md, docs/search-ui-react.standardfacetscssclasses.md, docs/search-ui-react.standardfacetsprops.md, etc/search-ui-react.api.md, package.json, src/components/FacetProps.tsx, src/components/Facets.tsx, src/components/HierarchicalFacets.tsx, src/components/NumericalFacets.tsx, src/components/StandardFacets.tsx, src/utils/filterutils.tsx, tests/components/Facets.test.tsx, tests/components/StandardFacet.stories.tsx
This change allows users to provide css classes for FilterGroup on the Facets level. If same css classes are provided on the singular facet level, the latter will be used.
J=BACK-2306
TEST=auto,manual
Added a test for this.
Also manually confirmed the behavior.
=> Add Facets Level Css Support for FilterGroup

THIRD-PARTY-NOTICES, package-lock.json, package.json, src/components/FeaturedSnippetDirectAnswer.tsx, test-site/package-lock.json
J=BACK-2241
TEST=manual
ran test-site of search-ui-react with entity that had formatted RichTextv2 data and verified that it was rendered properly
=> add support to display richtextv2 and markdown that has been converted to HTML

test-site/package-lock.json, test-site/package.json, test-site/src/components/HTMLExampleCard.tsx, test-site/src/components/MarkdownExampleCard.tsx, test-site/src/styles/resetStyles.css
Added example cards to render converter HTML and Markdown strings in search results
J=BACK-2395
T=manual
Manually ran test-site with each of the example cards, searching for entities that had the associated data type
=> Added example cards for HTML and Markdown Rendering

THIRD-PARTY-NOTICES, package-lock.json, package.json, test-site/package-lock.json
A few of the imports slipped through the cracks. This change fixes them
J=BACK-2545
TEST=manual
Confirmed this still works with the latest version of pages
=> Fix some package.json imports

THIRD-PARTY-NOTICES, package-lock.json, package.json
New version has `queryDurationMillis` as an optional field of VerticalResults
J=CLIP-1226
TEST=auto,manual
ran `npm run test`.
temporarily added GDA to ProductsPage in test site and verified that the appropriate gda content shows up after a vertical search.
=> update search-headless-react dependencies version to 2.5.0-beta.3

.github/workflows/main.yml
Ubuntu 20.04 for Github Actions is being deprecated and will be fully unsupported on 2025-04-01. Update our semgrep action to the latest version.
=> update semgrep action to use ubuntu-latest
